### PR TITLE
Flutter App?

### PR DESCRIPTION
**Pull request by mjarkk**
Todo:
- [ ] Correctly handle bluetooth connects, disconnects and reconnects
- [x] Login
- [x] Logout
- [x] App icon / Name (Thanks @sanderDijkxhoorn)
- [ ] Information
  - [x] Battery percentage
  - [ ] Is charging
  - [ ] Is locked
- [ ] Controls
  - [x] Assistance level
  - [x] Speed limit
  - [x] Bell sound
  - [ ] Lights
    - [x] On/Off
    - [x] Auto
      - [ ]  Calibrate
  - [ ] Gears
    - [ ] Default 2 presets
    - [ ] Custom shift points
    - [ ] Manual shifting 
  - [ ] Wake sound on/off
  - [ ] Unlocking
    - [x] Unlock button in app
    - [ ] Unlock bike with single tap bike's unlock button
    - [ ] Sound on/off
  - [ ] Alarm on/off
  - [ ] Set backup code

Bugs:
- [x] App needs to be closed and re-opened after login to get all bikes

### CODE REVIEW

**Review by sanderDijkxhoorn — COMMENTED** [review]
Hmm when I started with a fresh folder and cloned the project it said that is already included with the materials package.

Upon removing the import the app builds and works.

image

**Comment by sanderDijkxhoorn** [comment]
What do you mean by (TODO)
-> Controls
 -> Lights
  -> Configure auto

**Comment by sanderDijkxhoorn** [comment]
> Hmm when I started with a fresh folder and cloned the project it said that is already included with the materials package and the app build without any trouble 🤔

image

**Comment by mjarkk** [comment]
> Hmm when I started with a fresh folder and cloned the project it said that is already included with the materials package.
>
> Upon removing the import the app builds and works.

I had the opioids problem where i cannot build the program without that package imported??
This is sus

**Comment by mjarkk** [comment]
> What do you mean by (TODO)
> -> Controls
> --> Lights
> ---> Configure auto

There is an option in the vm app for automatically turning on the lights based on the amount of light outside.
That option is configurable in the vm app.

**Comment by sanderDijkxhoorn** [comment]
> > What do you mean by (TODO)
> > -> Controls
> > --> Lights
> > ---> Configure auto
> 
> There is an option in the vm app for automatically turning on the lights based on the amount of light outside. That option is configurable in the vm app.

11C5F982-F125-46CB-9476-5349BF854E2A

So I guess you mean the calibrate option? Auto is already implemented. 

409B00CF-7479-4A0D-AB10-CD47206E1FEE

**Comment by sanderDijkxhoorn** [comment]
> > Hmm when I started with a fresh folder and cloned the project it said that is already included with the materials package.
> > Upon removing the import the app builds and works.
> 
> I had the opioids problem where i cannot build the program without that package imported?? This is sus

Try removing the folder and cloning again or try the flutter pub get command you might have an older version installed?

**Comment by mjarkk** [comment]
> So I guess you mean the calibrate option? Auto is already implemented.

Yes that's what i meant i have updated the todo list

> Try removing the folder and cloning again or try the flutter pub get command you might have an older version installed?
>
> Also check if you have the latest version of Flutter
To upgrade run:
flutter upgrade

I was working on the app on windows and it seemed like i was running a outdated version of flutter. I'm now getting the same error as you and have reverted the change i made earlier :)

**Comment by sanderDijkxhoorn** [comment]
> > So I guess you mean the calibrate option? Auto is already implemented.
> 
> Yes that's what i meant i have updated the todo list
> 
> > Try removing the folder and cloning again or try the flutter pub get command you might have an older version installed?
> > Also check if you have the latest version of Flutter
> > To upgrade run:
> > flutter upgrade
> 
> I was working on the app on windows and it seemed like i was running a outdated version of flutter. I'm now getting the same error as you and have reverted the change i made earlier :)

👍

**Comment by sanderDijkxhoorn** [comment]
Why did you close the app PR? 

I still want to try and integrate the bell upload function.

**Pull request closed without merging**
